# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ExampleRecorder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenCV', '~> 4.3'

  target 'ExampleRecorderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
